# Site settings
author: Sarah Anderson
title: 404-blog-not-found
header-img: img/home-bg.png
email: saranderson13@gmail.com
copyright_name: Sarah Anderson
description: > # this means to ignore newlines until "baseurl:"
  An equally nondescript name for the blog formerly known as Untitled.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saranderson13

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
